TrajectoryPlannerROS:

    # Robot Configuration Parameters
    acc_lim_x: 5.0
    acc_lim_y: 0.0
    acc_lim_theta: 10.3
    acc_lim_theta: 20.0

    max_vel_x: 0.4
    min_vel_x: 0.02

    max_vel_y: 0.0
    min_vel_y: 0.0

    max_vel_theta: 0.8
    min_vel_theta: -0.8
    max_rotational_vel: 0.8
    min_in_place_vel_theta: 0.4
    max_vel_theta: 2.0
    min_vel_theta: -2.0
    max_rotational_vel: 2.0
    min_in_place_vel_theta: 0.04

    escape_vel: -0.1
    holonomic_robot: false

    # Goal Tolerance Parameters
    xy_goal_tolerance: 0.1
    yaw_goal_tolerance: 0.02
    latch_xy_goal_tolerance: true

    # Forward Simulation Parameters
    sim_time: 1.7
    sim_granularity: 0.05
    angular_sim_granularity: 0.08
    vx_samples: 3
    sim_granularity: 0.025
    angular_sim_granularity: 0.05
    vx_samples: 5
    vtheta_samples: 20
    controller_frequency: 10

    # Trajectory Scoring Parameters    
    meter_scoring: true # Whether the gdist_scale and pdist_scale parameters should assume that goal_distance and path_distance are expressed in units of meters or cells. Cells are assumed by default (false).
    occdist_scale:  0.01 #The weighting for how much the controller should attempt to avoid obstacles. default 0.01
    pdist_scale: 1.25  #     The weighting for how much the controller should stay close to the path it was given . default 0.6
    gdist_scale: 0.25 #     The weighting for how much the controller should attempt to reach its local goal, also controls speed  default 0.8

    heading_lookahead: 0.30  #How far to look ahead in meters when scoring different in-place-rotation trajectories
    heading_scoring: false  #Whether to score based on the robot's heading to the path or its distance from the path. default false
    heading_scoring_timestep: 0.8   #How far to look ahead in time in seconds along the simulated trajectory when using heading scoring (double, default: 0.8)
    dwa: false #Whether to use the Dynamic Window Approach (DWA)_ or whether to use Trajectory Rollout
    simple_attractor: false
    publish_cost_grid_pc: true

    #Oscillation Prevention Parameters
    oscillation_reset_dist: 0.07 #How far the robot must travel in meters before oscillation flags are reset (double, default: 0.05)
    escape_reset_dist: 0.01
    escape_reset_theta: 0.01
