map_type: costmap
meter_scoring: true

obstacle_range: 3.0
raytrace_range: 3.5

publish_voxel_map: false
transform_tolerance: 0.5

footprint: [[0.23, -0.265], [0.315, -0.14], [0.315, 0.14], [0.23, 0.265], [-0.23, 0.265], [-0.315, 0.14], [-0.315, -0.14], [-0.23, -0.265]]
#footprint: [[-0.315, -0.14], [-0.315, 0.14], [-0.22, 0.265], [0.22, 0.265], [0.315, 0.14], [0.315, -0.14], [0.22, -0.265], [-0.22, -0.265]]
footprint_padding: 0.01

obstacle_layer:
  observation_sources: scan
  scan: {sensor_frame: base_laser_link, data_type: LaserScan, topic: scan, marking: true, clearing: true, obstacle_range: 3.0, raytrace_range: 3.5}

inflation_layer:
  inflation_radius: 0.30

static_layer:
  enabled: true