mobile_base_controller:
  type        : "diff_drive_controller/DiffDriveController"
  left_wheel  : 'wheel_left_joint'
  right_wheel : 'wheel_right_joint'
  publish_rate: 50.0
  pose_covariance_diagonal : [0.001, 0.001, 1.0e-3, 1.0e-3, 1.0e-3, 0.01]
  twist_covariance_diagonal: [0.001, 0.001, 1.0e-3, 1.0e-3, 1.0e-3, 0.01]

  wheel_separation_multiplier: 1.000
  wheel_radius_multiplier    : 1.000

  enable_pose_covariance_update: true
  error_constant_left : 0.0
  error_constant_right: 0.0

  enable_odom_tf: false

  # Velocity commands timeout [s]
  cmd_vel_timeout: 0.5

  # Base frame_id
  base_frame_id: base_footprint

  # Preserve turning radius when limiting speed/acceleration/jerk
  preserve_turning_radius: true

  # Publish limited velocity
  publish_cmd: false

  # Publish wheel data
  publish_wheel_data: false

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : false
      max_velocity           :  2.0 # m/s
      min_velocity           : -2.0 # m/s
      has_acceleration_limits: false
      max_acceleration       :  6.0 # m/s^2
      has_jerk_limits        : false
      max_jerk               :  1.0 # m/s^3
  angular:
    z:
      has_velocity_limits    : false
      max_velocity           : !degrees 200.0
      has_acceleration_limits: false
      max_acceleration       : !degrees 200.0
      has_jerk_limits        : false
      max_jerk               : !degrees 600.0

mrp2_joint_publisher:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50

ekf_localization:
  frequency: 50
  odom0: /mobile_base_controller/odom
  odom0_config: [true, true, false,
                 false, false, false,
                 true, true, true,
                 false, false, true]
  odom0_differential: true
  imu0: /imu/data
  imu0_config: [false, false, false,
                true, true, true,
                false, false, false,
                true, true, true]
  imu0_differential: false
  odom_frame: odom
  base_link_frame: base_footprint
  world_frame: odom
  two_d_mode: true